services:
  geodispatch-app:
    container_name: geodispatch-dev
    volumes:
      - .:/public_html
      - /public_html/vendor
    environment:
      APP_ENV: local
      APP_DEBUG: true
    ports:
      - "5000:8000"







