services:
  geodispatch-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: geodispatch:latest #give image name instead the default
    env_file:
      - .env


  db:
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      POSTGRES_DB: geodispatch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:

